version: '3.7'

services:
  nginx:
    image: {{ env.NGINX_IMAGE }}
    ports:
      - '80:80'
      - '443:443'
    restart: always
    environment:
      YC_SA_JSON_CREDENTIALS: >
        {{ env.YC_SA_JSON_CREDENTIALS }}
      YC_FOLDER_ID: {{ env.YC_FOLDER_ID }}
      YC_CERTIFICATE_ID: {{ env.YC_CERTIFICATE_ID }}
    depends_on:
      - backend

  backend:
    image: {{ env.BACKEND_IMAGE }}
    restart: always
