name: Deploy extension to stores

on: workflow_dispatch

jobs:
  build-all:
    uses: ./.github/workflows/build.yml

  firefox:
    needs: build-all
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-ci
          path: ./packages/syncwatch-extension/.output

      - name: Build Extension for Firefox
        id: web-ext-build
        uses: kewisch/action-web-ext@v1
        with:
          cmd: build
          source: ./packages/syncwatch-extension/.output/firefox-mv2

      - name: "Sign & publish"
        id: web-ext-sign
        uses: kewisch/action-web-ext@main
        with:
          cmd: sign
          channel: listed
          source: ${{ steps.web-ext-build.outputs.target }}
          apiKey: ${{ secrets.FIREFOX_API_KEY }}
          apiSecret: ${{ secrets.FIREFOX_CLIENT_SECRET }}

      - name: Drop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "Firefox Artefacts"
          path: ${{ steps.web-ext-build.outputs.target }}

  chrome:
    needs: build-all
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v4

      - uses: actions/download-artifact@v4
        with:
          name: build-ci
          path: ./packages/syncwatch-extension/.output/chrome-mv3

      - name: Pack extension
        uses: TheDoctor0/zip-release@0.4.1
        with:
          filename: ./SyncWatchExtension.zip
          path: ./packages/syncwatch-extension/.output/chrome-mv3

      - name: Publish to Chrome Webstore
        uses: trmcnvn/chrome-addon@v2
        with:
          extension: ggiafipgeeaaahnjamgpjcgkdpanhddg
          zip: ./SyncWatchExtension.zip
          client-id: ${{ secrets.GOOGLE_CLIENT_ID }}
          client-secret: ${{ secrets.GOOGLE_CLIENT_SECRET }}
          refresh-token: ${{ secrets.GOOGLE_REFRESH_TOKEN }}

      - name: Upload artifact
        uses: xresloader/upload-to-github-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          file: ./SyncWatchExtension.zip
          tags: true
          draft: false

      - name: Drop artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "Chrome Artifacts"
          path: ./SyncWatchExtension.zip
